version: '3.7'

services:

  cache:
    image: redis:latest
    restart: always
    volumes:
      - ./data/cache:/data/

  db:
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0:8000
    restart: always
    ports:
      - "8000:8000" 
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=backend.core.settings.prod
      - POSTGRES_DB=postgres  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache
