# Generated by Django 5.0.2 on 2024-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_articles_ar_topic_i_6def1c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='article',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
