# Generated by Django 5.0.2 on 2024-02-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'articles',
            '0003_remove_content_article_remove_content_content_type_and_more',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='status',
            new_name='is_active',
        ),
    ]
