# Generated by Django 5.0.2 on 2024-02-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_status_article_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(
                fields=['slug'], name='articles_ar_slug_452037_idx'
            ),
        ),
    ]
