# Generated by Django 5.0.2 on 2024-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_articles_ar_slug_452037_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['topic'], name='articles_ar_topic_i_6def1c_idx'),
        ),
    ]
